### ISSUE TITLE
How do you reference Firebase?

### ISSUE THREAD

**Issue by gigocabrera** [carlospaelinck/ionic-2-app#3]
I see you have the following code in the `firebase.service.js` file 

`import * as Firebase from 'firebase'`

but I don't see a reference to Firebase API

`<script src="https://cdn.firebase.com/js/client/2.4.1/firebase.js"></script>`

How do you reference Firebase? (sorry if this is a stupid question but I'm new with this technology)

**Comment by princefr** [comment]
hi,
he installed the firebase node modules with `npm install firebase` , and simply import it

**Comment by gigocabrera** [comment]
@princefr you're the best. Thanks!
So when Firebase releases a new update all I have to do is run that again?

`npm install firebase`

**Comment by carlospaelinck** [comment]
Yes. You can also run `npm outdated` to see what's changed.
