### ISSUE TITLE
Getting the following error when I try to run the app

### ISSUE THREAD

**Issue by gigocabrera** [carlospaelinck/ionic-2-app#4]
I'm getting the following error when I try to run the app with `ionic serve`

![ionic-2-app-error](https://cloud.githubusercontent.com/assets/6364855/13852875/a2a3872e-ec3a-11e5-9ff4-319dbb9ce41f.png)

**Comment by carlospaelinck** [comment]
Yes, the node module for ionic changed and I missed the config. I pushed a fix. Good find.

**Comment by gigocabrera** [comment]
Awesome, thank you!
